### ISSUE TITLE
Current problems (tracking issue)

### ISSUE THREAD

**Issue by robinhad** [robinhad/ukrainian-tts#35]
Priority list:
- [ ] Select audio tempo https://github.com/robinhad/ukrainian-tts/issues/39
- [ ] Memory leak https://github.com/robinhad/ukrainian-tts/issues/30
- [ ] Handling of numbers https://github.com/robinhad/ukrainian-tts/issues/21
- [ ] New stress model https://github.com/robinhad/ukrainian-tts/issues/15
- [ ] Edge cases for text formatter https://github.com/robinhad/ukrainian-tts/issues/19
- [ ] Switch to phonemizer https://github.com/robinhad/ukrainian-tts/issues/36
