### ISSUE TITLE
Model improvement checklist

### ISSUE THREAD

**Issue by robinhad** [robinhad/ukrainian-tts#4]
- [x] Add Ukrainian accentor - https://github.com/egorsmkv/ukrainian-accentor
- [ ] Fine-tune from existing checkpoint (e.g. VITS Ljspeech)
- [ ] Try to increase `fft_size`, `hop_length` to match sample_rate accordingly
- [ ] Include more dataset samples into model
